apiVersion: v1
kind: ConfigMap
metadata:
  name: ccm-api-config
  namespace: pulsedev-ccm
data:
  DATABASE_URL: "postgresql://postgres@postgres-service:5432/pulsedev_ccm"
  REDIS_URL: "redis://redis-service:6379"
  CORS_ORIGINS: "*"
  LOG_LEVEL: "info"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccm-api
  namespace: pulsedev-ccm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ccm-api
  template:
    metadata:
      labels:
        app: ccm-api
    spec:
      containers:
      - name: ccm-api
        image: pulsedev-ccm-api:latest
        imagePullPolicy: Never  # For local development
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pulsedev-secrets
              key: postgres-password
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: pulsedev-secrets
              key: jwt-secret
        envFrom:
        - configMapRef:
            name: ccm-api-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "125m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: ccm-api-service
  namespace: pulsedev-ccm
spec:
  selector:
    app: ccm-api
  ports:
  - port: 8000
    targetPort: 8000
  type: LoadBalancer