global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: ""

replicaCount:
  api: 2
  frontend: 2

image:
  api:
    repository: ghcr.io/yourusername/pulsedev-plus-api
    tag: "latest"
    pullPolicy: IfNotPresent
  frontend:
    repository: ghcr.io/yourusername/pulsedev-plus-frontend
    tag: "latest"
    pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  api:
    type: ClusterIP
    port: 8000
  frontend:
    type: ClusterIP
    port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: pulsedev.yourdomain.com
      paths:
        - path: /api
          pathType: Prefix
          service: api
        - path: /
          pathType: Prefix
          service: frontend
  tls:
    - secretName: pulsedev-tls
      hosts:
        - pulsedev.yourdomain.com

resources:
  api:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 125m
      memory: 256Mi
  frontend:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

postgresql:
  enabled: true
  auth:
    postgresPassword: "password"
    username: "postgres"
    password: "password"
    database: "pulsedev_ccm"
  image:
    repository: timescale/timescaledb
    tag: latest-pg15
  primary:
    persistence:
      enabled: true
      size: 10Gi

redis:
  enabled: true
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      size: 8Gi

monitoring:
  prometheus:
    enabled: true
  grafana:
    enabled: true
    adminPassword: "admin"

secrets:
  jwtSecret: "your-jwt-secret-key"
  encryptionKey: "your-encryption-key"

config:
  corsOrigins: "*"
  logLevel: "info"